
# Basic dependabot.yml file with
# minimum configuration for two package managers

version: 2
updates:
  # Enable version updates for mix
  - package-ecosystem: "mix"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependabot-update"