name: Kubernetes Compatibility Matrix
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  KUBECONFIG: /home/runner/.kube/config

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        k8s_version: [v1.22.15, v1.23.13, v1.24.7, v1.25.3, v1.26.0]
        otp: [25.x]
        elixir: [1.14.x]
    steps:
      - uses: engineerd/setup-kind@v0.5.0
        id: kind
        with:
          version: v0.17.0
          image: kindest/node:${{ matrix.k8s_version }}
      - uses: actions/checkout@v3.5.2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}

      - name: Retrieve Build Cache
        uses: actions/cache@v3
        id: build-folder-cache
        with:
          path: _build
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-build-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

      - name: Retrieve Mix Dependencies Cache
        uses: actions/cache@v3
        id: mix-cache
        with:
          path: deps
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

      - run: mix local.rebar --force
      - run: mix local.hex --force
      - run: mix deps.get
      - name: Run Integration Tests
        run: |
          MIX_ENV=test mix compile
          MIX_ENV=test mix bonny.gen.manifest -o - | kubectl apply -f -
          TEST_WAIT_TIMEOUT=10000 TEST_KUBECONFIG=$KUBECONFIG mix test --only integration --timeout 12000
