name: Kubernetes Compatibility Matrix
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  KUBECONFIG: /home/runner/.kube/config

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        k8s_version: [v1.24.7, v1.25.3, v1.26.0, v1.27.3]
    steps:
      - uses: engineerd/setup-kind@v0.5.0
        id: kind
        with:
          version: v0.17.0
          image: kindest/node:${{ matrix.k8s_version }}
      - uses: actions/checkout@v4.1.5
      - uses: erlef/setup-beam@v1
        with:
          version-file: .tool-versions
          version-type: strict
          install-rebar: true
          install-hex: true

      - name: Retrieve Build Cache
        uses: actions/cache@v4
        id: build-folder-cache
        with:
          path: _build
          key: ${{ runner.os }}-${{ steps.beam.outputs.otp-version }}-${{ steps.beam.outputs.elixir-version }}-build-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

      - name: Retrieve Mix Dependencies Cache
        uses: actions/cache@v4
        id: mix-cache
        with:
          path: deps
          key: ${{ runner.os }}-${{ steps.beam.outputs.otp-version }}-${{ steps.beam.outputs.elixir-version }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

      - run: mix deps.get
      - name: Run Integration Tests
        run: |
          MIX_ENV=test mix compile
          MIX_ENV=test mix bonny.gen.manifest -o - | kubectl apply -f -
          TEST_WAIT_TIMEOUT=10000 TEST_KUBECONFIG=$KUBECONFIG mix test --only integration --timeout 12000
