name: Kubernetes Compatibility Matrix
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        k8s_version: [v1.29.14, v1.30.10, v1.31.6, v1.32.3, v1.33.0]
    steps:
      - uses: actions/checkout@v5.0.0

      - name: Setup Mise JDX
        run: |
          curl https://mise.run | sh
          echo "$HOME/.local/share/mise/bin" >> $GITHUB_PATH
          echo "$HOME/.local/share/mise/shims" >> $GITHUB_PATH
          echo "eval \"\$(mise activate bash)\"" >> ~/.bash_profile

      - name: Setup Kind
        run: mise run setup-kind --image kindest/node:${{ matrix.k8s_version }}

      - name: Install Hex
        run: MIX_ENV=test mise x elixir erlang -- mix local.hex --force

      - name: Retrieve Build Cache
        uses: actions/cache@v4
        id: build-folder-cache
        with:
          path: _build
          key: ${{ runner.os }}-${{ steps.beam.outputs.otp-version }}-${{ steps.beam.outputs.elixir-version }}-build-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

      - name: Retrieve Mix Dependencies Cache
        uses: actions/cache@v4
        id: mix-cache
        with:
          path: deps
          key: ${{ runner.os }}-${{ steps.beam.outputs.otp-version }}-${{ steps.beam.outputs.elixir-version }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

      - name: Run Integration Tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mise run integration-tests-ci
